"""CSV export for ViDrive TCO results."""
import csv
import re
from pathlib import Path
from datetime import date
from src.calculations import is_area1_metro


def _safe_id(value: str) -> str:
    """Sanitize an external identifier for safe use in a file name (no traversal)."""
    return re.sub(r'[^A-Za-z0-9_.-]', '_', str(value))[:64]


def _fmt_vnd(amount: float | int) -> str:
    """Format as VND with commas."""
    return f"{amount:,.0f}"


def _area_name(area: int, city: str) -> str:
    """Return the human-readable area name with metro sub-tier support."""
    base = {
        1: "Area 1 (Central City)",
        2: "Area 2 (Provincial City)",
        3: "Area 3 (Rural/District)",
    }.get(area, "Area 2")
    if area == 1 and city and is_area1_metro(city):
        return "Area 1 (Metro — Hanoi/HCMC core)"
    return base


def export_single_csv(car_id: str, years: int, res: dict, city: str, km: int,
                      area: int, ratio: float, show_opp: bool, loan: dict | None = None,
                      filename: str | None = None, target_dir: "Path | None" = None) -> str:
    """Export single car TCO result to CSV.

    Returns the path to the generated CSV file.
    """
    if filename is None:
        filename = f"vidrive_{_safe_id(car_id)}_{date.today().strftime('%Y%m%d')}.csv"
    if target_dir is None:
        target_dir = Path.cwd()
    filepath = Path(target_dir) / filename
    rows: list[list[str]] = []

    # Header
    rows.append(["Cost Component", car_id.upper()])

    # Summary
    rows.append(["On-road Price", _fmt_vnd(res["on_road"])])
    rows.append([f"Net TCO ({years} yr)", _fmt_vnd(res["tco"])])
    if show_opp:
        rows.append(["Opportunity Cost", _fmt_vnd(res["opp_cost"])])
        rows.append(["True Financial Impact", _fmt_vnd(res["true_financial_impact"])])
    rows.append(["Monthly Average", _fmt_vnd(res["monthly"])])
    rows.append([])

    # Initial Outlay
    rows.append(["1. INITIAL OUTLAY", ""])
    rows.append(["MSRP Price", _fmt_vnd(res["price"])])
    rows.append(["Registration Tax", _fmt_vnd(res["reg_tax"])])
    rows.append(["Total Outlay", _fmt_vnd(res["on_road"])])
    rows.append([])

    # Operating Costs
    rows.append(["2. OPERATING COSTS", ""])
    rows.append(["Fuel / Energy", _fmt_vnd(res["fuel"])])
    rows.append(["Maintenance", _fmt_vnd(res["maint"])])
    rows.append(["Periodic Inspection (đăng kiểm)", _fmt_vnd(res.get("inspection_periodic", 0))])
    rows.append(["Insurance & Fees", _fmt_vnd(res["legal"])])
    rows.append(["Total Operating", _fmt_vnd(res["operating"])])
    pt = res.get("parking_toll")
    if pt:
        rows.append(["Parking & Tolls (est.)", _fmt_vnd(pt["total_over_period"])])
        rows.append(["  Monthly Parking", _fmt_vnd(pt["monthly_parking"])])
        rows.append(["  Monthly Toll", _fmt_vnd(pt["monthly_toll"])])
    rows.append([])

    # Resale & Depreciation
    rows.append(["3. RESALE & DEPRECIATION", ""])
    rows.append(["Predicted Resale", _fmt_vnd(res["resale"])])
    rows.append(["Total Depreciation", _fmt_vnd(res["depreciation"])])
    rows.append(["Resale Method", res["resale_logic"]])
    rows.append([])

    # Loan
    if loan:
        rows.append(["4. LOAN / FINANCING PLAN", ""])
        rows.append(["Monthly Payment", _fmt_vnd(loan["monthly_payment"])])
        rows.append(["Total Interest", _fmt_vnd(loan["total_interest"])])
        rows.append(["Total Repayment", _fmt_vnd(loan["total_repayment"])])
        rows.append(["Effective Cost", _fmt_vnd(loan["effective_cost"])])
        rows.append([])

    # Assumptions
    rows.append(["ASSUMPTIONS", ""])
    rows.append(["City/Province", city.title()])
    rows.append(["Area", _area_name(area, city)])
    rows.append(["Annual KM", f"{km:,}"])
    rows.append(["Years", str(years)])
    rows.append(["City/Highway Split", f"{ratio*100:.0f}% / {100-ratio*100:.0f}%"])
    rows.append(["Opportunity Cost", "Yes" if show_opp else "No"])
    rows.append([])
    rows.append(["Generated by ViDrive TCO Calculator v1.0.0"])
    rows.append(["For informational purposes only. Not financial advice."])

    with filepath.open("w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerows(rows)

    return str(filepath)


def export_compare_csv(cars_data: list[str], results: list[dict], years: int,
                       city: str, km: int, area: int, ratio: float, show_opp: bool,
                        loans: list[dict] | None = None, filename: str | None = None,
                        target_dir: "Path | None" = None) -> str:
    """Export multi-car comparison to CSV.

    Returns the path to the generated CSV file.
    """
    if filename is None:
        filename = f"vidrive_compare_{date.today().strftime('%Y%m%d')}.csv"
    if target_dir is None:
        target_dir = Path.cwd()
    filepath = Path(target_dir) / filename
    car_ids = [c.upper() for c in cars_data]
    n = len(car_ids)
    rows: list[list[str]] = []

    # Header row
    header = ["Cost Component"] + car_ids
    rows.append(header)
    rows.append([])

    # Summary
    rows.append(["On-road Price"] + [_fmt_vnd(r["on_road"]) for r in results])
    rows.append([f"Net TCO ({years} yr)"] + [_fmt_vnd(r["tco"]) for r in results])
    if show_opp:
        rows.append(["Opportunity Cost"] + [_fmt_vnd(r["opp_cost"]) for r in results])
        rows.append(["True Financial Impact"] + [_fmt_vnd(r["true_financial_impact"]) for r in results])
    rows.append(["Monthly Average"] + [_fmt_vnd(r["monthly"]) for r in results])
    rows.append([])

    # Initial Outlay
    rows.append(["MSRP Price"] + [_fmt_vnd(r["price"]) for r in results])
    rows.append(["Registration Tax"] + [_fmt_vnd(r["reg_tax"]) for r in results])
    rows.append(["Total Outlay"] + [_fmt_vnd(r["on_road"]) for r in results])
    rows.append([])

    # Operating Costs
    rows.append(["Fuel / Energy"] + [_fmt_vnd(r["fuel"]) for r in results])
    rows.append(["Maintenance"] + [_fmt_vnd(r["maint"]) for r in results])
    rows.append(["Insurance & Fees"] + [_fmt_vnd(r["legal"]) for r in results])
    rows.append(["Total Operating"] + [_fmt_vnd(r["operating"]) for r in results])
    rows.append([])

    # Parking & Tolls
    rows.append(["Parking & Tolls (est.)"] + [_fmt_vnd(r.get("parking_toll", {}).get("total_over_period", 0)) for r in results])
    rows.append([])

    # Resale & Depreciation
    rows.append(["Predicted Resale"] + [_fmt_vnd(r["resale"]) for r in results])
    rows.append(["Total Depreciation"] + [_fmt_vnd(r["depreciation"]) for r in results])
    rows.append([])

    # Loan
    if loans:
        rows.append(["Monthly Payment"] + [_fmt_vnd(l["monthly_payment"]) for l in loans])
        rows.append(["Total Interest"] + [_fmt_vnd(l["total_interest"]) for l in loans])
        rows.append(["Total Repayment"] + [_fmt_vnd(l["total_repayment"]) for l in loans])
        rows.append(["Effective Cost"] + [_fmt_vnd(l["effective_cost"]) for l in loans])
        rows.append([])

    # Verdict
    rows.append([])
    min_idx = min(range(n), key=lambda i: results[i]["tco"])
    winner = car_ids[min_idx]
    rows.append([f"VERDICT: {winner} is the MOST ECONOMICAL", ""])
    for i in range(n):
        if i != min_idx:
            diff = results[i]["tco"] - results[min_idx]["tco"]
            rows.append([f"  {winner} saves {diff:,.0f} VND vs {car_ids[i]}", ""])

# Assumptions
    rows.append([])
    rows.append(["ASSUMPTIONS", ""])
    rows.append(["City/Province", city.title()])
    rows.append(["Area", _area_name(area, city)])
    rows.append(["Annual KM", f"{km:,}"])
    rows.append(["Years", str(years)])
    rows.append(["City/Highway Split", f"{ratio*100:.0f}% / {100-ratio*100:.0f}%"])
    rows.append(["Opportunity Cost", "Yes" if show_opp else "No"])
    rows.append([])
    rows.append(["Generated by ViDrive TCO Calculator v1.0.0"])
    rows.append(["For informational purposes only. Not financial advice."])

    with filepath.open("w", encoding="utf-8-sig", newline="") as f:
        writer = csv.writer(f, delimiter=';')
        writer.writerows(rows)

    return str(filepath)
